// This file is auto-generated by scripts/update-slides-list.ts
export const slides = [
  {
    "id": "digicre-advent-calender-2025",
    "title": "digicre-advent-calender-2025"
  },
  {
    "id": "what-is-accesibility",
    "title": "what-is-accesibility"
  },
  {
    "id": "example",
    "title": "Welcome to Slidev"
  },
  {
    "id": "slides/intoroducing-until-hidden",
    "title": "HTMLの新しい属性値hidden=&quot;until-found&quot;"
  }
] as const
