// This file is auto-generated by scripts/update-slides-list.ts
export const slides = [
  {
    "name": "cjk-font-fallback",
    "title": "スマホを英語にしたら日本語が「中国語」になった話",
    "path": "/slides/cjk-font-fallback/"
  },
  {
    "name": "digicre-advent-calender-2025",
    "title": "digicre-advent-calender-2025",
    "path": "/slides/digicre-advent-calender-2025/"
  },
  {
    "name": "example",
    "title": "Welcome to Slidev",
    "path": "/slides/example/"
  },
  {
    "name": "introducing-until-hidden",
    "title": "hidden=\"until-found\"を使ってアクセシブルな折りたたみを実装する",
    "path": "/slides/introducing-until-hidden/"
  },
  {
    "name": "what-is-accessibility",
    "title": "what-is-accesibility",
    "path": "/slides/what-is-accessibility/"
  }
] as const
