// This file is auto-generated by scripts/update-slides-list.ts
export const slides = [
  {
    "name": "digicre-advent-calender-2025",
    "title": "digicre-advent-calender-2025",
    "path": "/slides/digicre-advent-calender-2025/"
  },
  {
    "name": "example",
    "title": "Welcome to Slidev",
    "path": "/slides/example/"
  },
  {
    "name": "introducing-until-hidden",
    "title": "HTMLの新しい属性値hidden=\"until-found\"",
    "path": "/slides/introducing-until-hidden/"
  },
  {
    "name": "what-is-accessibility",
    "title": "what-is-accesibility",
    "path": "/slides/what-is-accessibility/"
  }
] as const
