import { promises as fs } from "fs";
import path from "path";

const __dirname = import.meta.dirname;

type SlideEntry = { name: string; title: string; date: string; path: string };

function extractField(markdown: string, key: string): string | null {
  const frontmatter = /^---\r?\n([\s\S]*?)\r?\n---/.exec(markdown);
  if (!frontmatter) return null;
  const field = new RegExp(`^${key}:\\s*(.+)\\s*$`, "m").exec(frontmatter[1]);
  if (!field) return null;
  return field[1].trim().replace(/^(['"])(.*)\1$/, "$2");
}

function toISODate(value: string | null): string {
  if (!value) return "";
  return value.replaceAll("/", "-");
}

async function collectSlides(slidesDir: string): Promise<SlideEntry[]> {
  const dirents = await fs.readdir(slidesDir, { withFileTypes: true });
  const entries: SlideEntry[] = [];
  for (const dirent of dirents) {
    if (!dirent.isDirectory()) continue;
    const slidesMd = path.join(slidesDir, dirent.name, "slides.md");
    let markdown: string;
    try {
      markdown = await fs.readFile(slidesMd, "utf-8");
    } catch {
      continue;
    }
    entries.push({
      name: dirent.name,
      title: extractField(markdown, "title") ?? dirent.name,
      date: toISODate(extractField(markdown, "eventDate")),
      path: `/slides/${dirent.name}/`,
    });
  }
  return entries.sort((a, b) => {
    if (a.date !== b.date) {
      if (!a.date) return 1;
      if (!b.date) return -1;
      return b.date.localeCompare(a.date);
    }
    return a.name.localeCompare(b.name);
  });
}

async function main() {
  const slidesDir = path.resolve(__dirname, "../slides");
  const targetFile = path.resolve(__dirname, "../home/src/slides.ts");
  try {
    const entries = await collectSlides(slidesDir);
    const content = `// This file is auto-generated by scripts/update-slides-list.ts
export const slides = ${JSON.stringify(entries, null, 2)} as const
`;
    await fs.writeFile(targetFile, content, "utf-8");
    console.log(`Generated ${targetFile} (${entries.length} slides)`);
  } catch (error) {
    console.error("Failed to update slides list:", error);
    process.exit(1);
  }
}

main();
