import { promises as fs } from "fs";
import path from "path";

const __dirname = import.meta.dirname;

type SlideEntry = { name: string; title: string; path: string };

function extractTitle(markdown: string): string | null {
  const frontmatter = /^---\r?\n([\s\S]*?)\r?\n---/.exec(markdown);
  if (!frontmatter) return null;
  const title = /^title:\s*(.+)\s*$/m.exec(frontmatter[1]);
  if (!title) return null;
  return title[1].trim().replace(/^(['"])(.*)\1$/, "$2");
}

async function collectSlides(slidesDir: string): Promise<SlideEntry[]> {
  const dirents = await fs.readdir(slidesDir, { withFileTypes: true });
  const entries: SlideEntry[] = [];
  for (const dirent of dirents) {
    if (!dirent.isDirectory()) continue;
    const slidesMd = path.join(slidesDir, dirent.name, "slides.md");
    let markdown: string;
    try {
      markdown = await fs.readFile(slidesMd, "utf-8");
    } catch {
      continue;
    }
    entries.push({
      name: dirent.name,
      title: extractTitle(markdown) ?? dirent.name,
      path: `/slides/${dirent.name}/`,
    });
  }
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

async function main() {
  const slidesDir = path.resolve(__dirname, "../slides");
  const targetFile = path.resolve(__dirname, "../home/src/slides.ts");
  try {
    const entries = await collectSlides(slidesDir);
    const content = `// This file is auto-generated by scripts/update-slides-list.ts
export const slides = ${JSON.stringify(entries, null, 2)} as const
`;
    await fs.writeFile(targetFile, content, "utf-8");
    console.log(`Generated ${targetFile} (${entries.length} slides)`);
  } catch (error) {
    console.error("Failed to update slides list:", error);
    process.exit(1);
  }
}

main();
