import { promises as fs } from "fs";
import path from "path";

async function collectSlides(
  rootDir: string,
  relativeDir = ""
): Promise<{ id: string; title: string }[]> {
  const currentDir = relativeDir ? path.join(rootDir, relativeDir) : rootDir;
  const dirents = await fs.readdir(currentDir, { withFileTypes: true });
  const htmlFile = dirents.find(
    (entry) => entry.isFile() && entry.name.endsWith(".html")
  );

  if (htmlFile && relativeDir) {
    const htmlPath = path.join(currentDir, htmlFile.name);
    const contentHtml = await fs.readFile(htmlPath, "utf-8");
    const match = /<title>([^<]+)<\/title>/.exec(contentHtml);
    const title = match ? match[1] : relativeDir;
    const id = relativeDir.split(path.sep).join("/");
    return [{ id, title }];
  }

  const entries: { id: string; title: string }[] = [];
  for (const dirent of dirents) {
    if (!dirent.isDirectory()) continue;
    const nextRelative = relativeDir
      ? path.join(relativeDir, dirent.name)
      : dirent.name;
    entries.push(...(await collectSlides(rootDir, nextRelative)));
  }
  return entries;
}

async function main() {
  const distDir = path.resolve(__dirname, "../dist");
  const targetFile = path.resolve(__dirname, "../home/src/slides.ts");
  try {
    const entries = await collectSlides(distDir);
    const content = `// This file is auto-generated by scripts/update-slides-list.ts
export const slides = ${JSON.stringify(entries, null, 2)} as const
`;
    await fs.writeFile(targetFile, content, "utf-8");
  } catch (error) {
    console.error("Failed to update slides list:", error);
    process.exit(1);
  }
}

main();
